
  create table "public"."answers" (
    "created_at" timestamp with time zone not null default now(),
    "submission_id" text not null,
    "question_id" text not null,
    "answer_data" jsonb not null
      );


alter table "public"."answers" enable row level security;


  create table "public"."question_judges" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "submission_id" text,
    "question_id" text,
    "status" public.judging_status,
    "judge_id" uuid
      );


alter table "public"."question_judges" enable row level security;


  create table "public"."questions" (
    "created_at" timestamp with time zone not null default now(),
    "submission_id" text not null,
    "question_id" text not null,
    "question_data" jsonb not null
      );


alter table "public"."questions" enable row level security;


  create table "public"."submissions" (
    "id" text not null,
    "queue_id" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."submissions" enable row level security;

alter table "public"."agent_configurations" alter column "id" drop identity;

alter table "public"."agent_configurations" alter column "id" set data type uuid using "id"::uuid;

CREATE UNIQUE INDEX agent_configurations_id_key ON public.agent_configurations USING btree (id);

CREATE UNIQUE INDEX answers_pkey ON public.answers USING btree (submission_id, question_id);

CREATE UNIQUE INDEX question_judges_pkey ON public.question_judges USING btree (id);

CREATE UNIQUE INDEX question_judging_statuses_question_id_submission_id_key ON public.questions USING btree (question_id, submission_id);

CREATE UNIQUE INDEX questions_pkey ON public.questions USING btree (submission_id, question_id);

CREATE UNIQUE INDEX submissions_pkey ON public.submissions USING btree (id);

alter table "public"."answers" add constraint "answers_pkey" PRIMARY KEY using index "answers_pkey";

alter table "public"."question_judges" add constraint "question_judges_pkey" PRIMARY KEY using index "question_judges_pkey";

alter table "public"."questions" add constraint "questions_pkey" PRIMARY KEY using index "questions_pkey";

alter table "public"."submissions" add constraint "submissions_pkey" PRIMARY KEY using index "submissions_pkey";

alter table "public"."agent_configurations" add constraint "agent_configurations_id_key" UNIQUE using index "agent_configurations_id_key";

alter table "public"."answers" add constraint "answers_question_id_submission_id_fkey" FOREIGN KEY (question_id, submission_id) REFERENCES public.questions(question_id, submission_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."answers" validate constraint "answers_question_id_submission_id_fkey";

alter table "public"."question_judges" add constraint "question_judges_judge_id_fkey" FOREIGN KEY (judge_id) REFERENCES public.agent_configurations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."question_judges" validate constraint "question_judges_judge_id_fkey";

alter table "public"."question_judges" add constraint "question_judges_question_id_submission_id_fkey" FOREIGN KEY (question_id, submission_id) REFERENCES public.questions(question_id, submission_id) not valid;

alter table "public"."question_judges" validate constraint "question_judges_question_id_submission_id_fkey";

alter table "public"."question_judges" add constraint "question_judges_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES public.submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."question_judges" validate constraint "question_judges_submission_id_fkey";

alter table "public"."questions" add constraint "judging_statuses_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES public.submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."questions" validate constraint "judging_statuses_submission_id_fkey";

alter table "public"."questions" add constraint "question_judging_statuses_question_id_submission_id_key" UNIQUE using index "question_judging_statuses_question_id_submission_id_key";

grant delete on table "public"."agent_configurations" to "postgres";

grant insert on table "public"."agent_configurations" to "postgres";

grant references on table "public"."agent_configurations" to "postgres";

grant select on table "public"."agent_configurations" to "postgres";

grant trigger on table "public"."agent_configurations" to "postgres";

grant truncate on table "public"."agent_configurations" to "postgres";

grant update on table "public"."agent_configurations" to "postgres";

grant delete on table "public"."answers" to "anon";

grant insert on table "public"."answers" to "anon";

grant references on table "public"."answers" to "anon";

grant select on table "public"."answers" to "anon";

grant trigger on table "public"."answers" to "anon";

grant truncate on table "public"."answers" to "anon";

grant update on table "public"."answers" to "anon";

grant delete on table "public"."answers" to "authenticated";

grant insert on table "public"."answers" to "authenticated";

grant references on table "public"."answers" to "authenticated";

grant select on table "public"."answers" to "authenticated";

grant trigger on table "public"."answers" to "authenticated";

grant truncate on table "public"."answers" to "authenticated";

grant update on table "public"."answers" to "authenticated";

grant delete on table "public"."answers" to "postgres";

grant insert on table "public"."answers" to "postgres";

grant references on table "public"."answers" to "postgres";

grant select on table "public"."answers" to "postgres";

grant trigger on table "public"."answers" to "postgres";

grant truncate on table "public"."answers" to "postgres";

grant update on table "public"."answers" to "postgres";

grant delete on table "public"."answers" to "service_role";

grant insert on table "public"."answers" to "service_role";

grant references on table "public"."answers" to "service_role";

grant select on table "public"."answers" to "service_role";

grant trigger on table "public"."answers" to "service_role";

grant truncate on table "public"."answers" to "service_role";

grant update on table "public"."answers" to "service_role";

grant delete on table "public"."question_judges" to "anon";

grant insert on table "public"."question_judges" to "anon";

grant references on table "public"."question_judges" to "anon";

grant select on table "public"."question_judges" to "anon";

grant trigger on table "public"."question_judges" to "anon";

grant truncate on table "public"."question_judges" to "anon";

grant update on table "public"."question_judges" to "anon";

grant delete on table "public"."question_judges" to "authenticated";

grant insert on table "public"."question_judges" to "authenticated";

grant references on table "public"."question_judges" to "authenticated";

grant select on table "public"."question_judges" to "authenticated";

grant trigger on table "public"."question_judges" to "authenticated";

grant truncate on table "public"."question_judges" to "authenticated";

grant update on table "public"."question_judges" to "authenticated";

grant delete on table "public"."question_judges" to "postgres";

grant insert on table "public"."question_judges" to "postgres";

grant references on table "public"."question_judges" to "postgres";

grant select on table "public"."question_judges" to "postgres";

grant trigger on table "public"."question_judges" to "postgres";

grant truncate on table "public"."question_judges" to "postgres";

grant update on table "public"."question_judges" to "postgres";

grant delete on table "public"."question_judges" to "service_role";

grant insert on table "public"."question_judges" to "service_role";

grant references on table "public"."question_judges" to "service_role";

grant select on table "public"."question_judges" to "service_role";

grant trigger on table "public"."question_judges" to "service_role";

grant truncate on table "public"."question_judges" to "service_role";

grant update on table "public"."question_judges" to "service_role";

grant delete on table "public"."questions" to "anon";

grant insert on table "public"."questions" to "anon";

grant references on table "public"."questions" to "anon";

grant select on table "public"."questions" to "anon";

grant trigger on table "public"."questions" to "anon";

grant truncate on table "public"."questions" to "anon";

grant update on table "public"."questions" to "anon";

grant delete on table "public"."questions" to "authenticated";

grant insert on table "public"."questions" to "authenticated";

grant references on table "public"."questions" to "authenticated";

grant select on table "public"."questions" to "authenticated";

grant trigger on table "public"."questions" to "authenticated";

grant truncate on table "public"."questions" to "authenticated";

grant update on table "public"."questions" to "authenticated";

grant delete on table "public"."questions" to "postgres";

grant insert on table "public"."questions" to "postgres";

grant references on table "public"."questions" to "postgres";

grant select on table "public"."questions" to "postgres";

grant trigger on table "public"."questions" to "postgres";

grant truncate on table "public"."questions" to "postgres";

grant update on table "public"."questions" to "postgres";

grant delete on table "public"."questions" to "service_role";

grant insert on table "public"."questions" to "service_role";

grant references on table "public"."questions" to "service_role";

grant select on table "public"."questions" to "service_role";

grant trigger on table "public"."questions" to "service_role";

grant truncate on table "public"."questions" to "service_role";

grant update on table "public"."questions" to "service_role";

grant delete on table "public"."submissions" to "anon";

grant insert on table "public"."submissions" to "anon";

grant references on table "public"."submissions" to "anon";

grant select on table "public"."submissions" to "anon";

grant trigger on table "public"."submissions" to "anon";

grant truncate on table "public"."submissions" to "anon";

grant update on table "public"."submissions" to "anon";

grant delete on table "public"."submissions" to "authenticated";

grant insert on table "public"."submissions" to "authenticated";

grant references on table "public"."submissions" to "authenticated";

grant select on table "public"."submissions" to "authenticated";

grant trigger on table "public"."submissions" to "authenticated";

grant truncate on table "public"."submissions" to "authenticated";

grant update on table "public"."submissions" to "authenticated";

grant delete on table "public"."submissions" to "postgres";

grant insert on table "public"."submissions" to "postgres";

grant references on table "public"."submissions" to "postgres";

grant select on table "public"."submissions" to "postgres";

grant trigger on table "public"."submissions" to "postgres";

grant truncate on table "public"."submissions" to "postgres";

grant update on table "public"."submissions" to "postgres";

grant delete on table "public"."submissions" to "service_role";

grant insert on table "public"."submissions" to "service_role";

grant references on table "public"."submissions" to "service_role";

grant select on table "public"."submissions" to "service_role";

grant trigger on table "public"."submissions" to "service_role";

grant truncate on table "public"."submissions" to "service_role";

grant update on table "public"."submissions" to "service_role";


  create policy "public table"
  on "public"."answers"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "public table"
  on "public"."questions"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "public table"
  on "public"."submissions"
  as permissive
  for all
  to public
using (true)
with check (true);



