create type "public"."judge_evaluation" as enum ('PASS', 'FAIL', 'INCONCLUSIVE');

create type "public"."judging_status" as enum ('RUNNING', 'QUEUED', 'FAILED', 'CANCELED', 'COMPLETE');

create type "public"."llm_model" as enum ('gpt-4o-mini', 'gpt-4o', 'gpt-4.1', 'gpt-4.1-mini');


  create table "public"."agent_configurations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "is_active" boolean not null,
    "model" public.llm_model not null,
    "rubric" text not null
      );


alter table "public"."agent_configurations" enable row level security;

CREATE UNIQUE INDEX agent_configurations_pkey ON public.agent_configurations USING btree (id);

alter table "public"."agent_configurations" add constraint "agent_configurations_pkey" PRIMARY KEY using index "agent_configurations_pkey";

alter table "public"."agent_configurations" add constraint "agent_configurations_rubric_check" CHECK ((length(rubric) <= 10000)) not valid;

alter table "public"."agent_configurations" validate constraint "agent_configurations_rubric_check";

grant delete on table "public"."agent_configurations" to "anon";

grant insert on table "public"."agent_configurations" to "anon";

grant references on table "public"."agent_configurations" to "anon";

grant select on table "public"."agent_configurations" to "anon";

grant trigger on table "public"."agent_configurations" to "anon";

grant truncate on table "public"."agent_configurations" to "anon";

grant update on table "public"."agent_configurations" to "anon";

grant delete on table "public"."agent_configurations" to "authenticated";

grant insert on table "public"."agent_configurations" to "authenticated";

grant references on table "public"."agent_configurations" to "authenticated";

grant select on table "public"."agent_configurations" to "authenticated";

grant trigger on table "public"."agent_configurations" to "authenticated";

grant truncate on table "public"."agent_configurations" to "authenticated";

grant update on table "public"."agent_configurations" to "authenticated";

grant delete on table "public"."agent_configurations" to "postgres";

grant insert on table "public"."agent_configurations" to "postgres";

grant references on table "public"."agent_configurations" to "postgres";

grant select on table "public"."agent_configurations" to "postgres";

grant trigger on table "public"."agent_configurations" to "postgres";

grant truncate on table "public"."agent_configurations" to "postgres";

grant update on table "public"."agent_configurations" to "postgres";

grant delete on table "public"."agent_configurations" to "service_role";

grant insert on table "public"."agent_configurations" to "service_role";

grant references on table "public"."agent_configurations" to "service_role";

grant select on table "public"."agent_configurations" to "service_role";

grant trigger on table "public"."agent_configurations" to "service_role";

grant truncate on table "public"."agent_configurations" to "service_role";

grant update on table "public"."agent_configurations" to "service_role";


  create policy "public table"
  on "public"."agent_configurations"
  as permissive
  for all
  to public
using (true)
with check (true);



